/**
 * Created by 75932 on 2017/4/25.
 */
export const weatherIcon = {
    code100: require('../../assets/images/weather/100.png'),
    code101: require('../../assets/images/weather/101.png'),
    code102: require('../../assets/images/weather/102.png'),
    code103: require('../../assets/images/weather/103.png'),
    code104: require('../../assets/images/weather/104.png'),
    code200: require('../../assets/images/weather/200.png'),
    code201: require('../../assets/images/weather/201.png'),
    code202: require('../../assets/images/weather/202.png'),
    code203: require('../../assets/images/weather/203.png'),
    code204: require('../../assets/images/weather/204.png'),
    code205: require('../../assets/images/weather/205.png'),
    code206: require('../../assets/images/weather/206.png'),
    code207: require('../../assets/images/weather/207.png'),
    code208: require('../../assets/images/weather/208.png'),
    code209: require('../../assets/images/weather/209.png'),
    code210: require('../../assets/images/weather/210.png'),
    code211: require('../../assets/images/weather/211.png'),
    code212: require('../../assets/images/weather/212.png'),
    code213: require('../../assets/images/weather/213.png'),
    code300: require('../../assets/images/weather/300.png'),
    code301: require('../../assets/images/weather/301.png'),
    code302: require('../../assets/images/weather/302.png'),
    code303: require('../../assets/images/weather/303.png'),
    code304: require('../../assets/images/weather/304.png'),
    code305: require('../../assets/images/weather/305.png'),
    code306: require('../../assets/images/weather/306.png'),
    code307: require('../../assets/images/weather/307.png'),
    code308: require('../../assets/images/weather/308.png'),
    code309: require('../../assets/images/weather/309.png'),
    code310: require('../../assets/images/weather/310.png'),
    code311: require('../../assets/images/weather/311.png'),
    code312: require('../../assets/images/weather/312.png'),
    code313: require('../../assets/images/weather/313.png'),
    code400: require('../../assets/images/weather/400.png'),
    code401: require('../../assets/images/weather/401.png'),
    code402: require('../../assets/images/weather/402.png'),
    code403: require('../../assets/images/weather/403.png'),
    code404: require('../../assets/images/weather/404.png'),
    code405: require('../../assets/images/weather/405.png'),
    code406: require('../../assets/images/weather/406.png'),
    code407: require('../../assets/images/weather/407.png'),
    code500: require('../../assets/images/weather/500.png'),
    code501: require('../../assets/images/weather/501.png'),
    code502: require('../../assets/images/weather/502.png'),
    code503: require('../../assets/images/weather/503.png'),
    code504: require('../../assets/images/weather/504.png'),
    code507: require('../../assets/images/weather/507.png'),
    code508: require('../../assets/images/weather/508.png'),
    code900: require('../../assets/images/weather/900.png'),
    code901: require('../../assets/images/weather/901.png'),
    code999: require('../../assets/images/weather/999.png'),
}